name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 0 * * *'  # Ежедневно в 00:00 UTC
  workflow_dispatch:      # Разрешает ручной запуск

permissions:
  contents: write        # Даем права на запись

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история коммитов

      # Шаг 2: Создаем базовый файл если отсутствует
      - name: Create playlist file
        run: |
          if [ ! -f ru.m3u ]; then
            echo "#EXTM3U" > ru.m3u
          fi

      # Шаг 3: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Шаг 4: Запускаем скрипт обновления
      - name: Run update script
        run: |
          pip install requests
          python update.py

      # Шаг 5: Фильтруем нерабочие каналы
      - name: Filter dead channels
        run: |
          sudo apt-get install -y npm
          npm install -g iptv-checker
          iptv-checker -i ru.m3u -o temp.m3u --timeout 3000
          mv temp.m3u ru.m3u

      # Шаг 6: Пушим изменения
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ru.m3u
          git pull --rebase origin main
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')" || echo "No changes"
          git push origin main
