name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 0 * * *'  # Ежедневно в 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create playlist file
        run: |
          if [ ! -f ru.m3u ]; then
            echo "#EXTM3U" > ru.m3u
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run update script
        run: |
          pip install requests
          python update.py

      - name: Filter dead channels
        run: |
          # Устанавливаем только необходимые пакеты
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          
          # Альтернативный вариант проверки с ffmpeg
          while IFS= read -r line; do
            if [[ "$line" == http* ]]; then
              if ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$line" >/dev/null 2>&1; then
                echo "$line"
              fi
            else
              echo "$line"
            fi
          done < ru.m3u > temp.m3u
          mv temp.m3u ru.m3u

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ru.m3u
          git diff-index --quiet HEAD || {
            git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')"
            git pull --ff-only
            git push origin main
          }
