name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - run: echo "#EXTM3U" > ru.m3u
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests
      - run: python update.py
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ru.m3u
          name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - run: echo "#EXTM3U" > ru.m3u
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - run: pip install requests
      - run: python update.py

      ### ↓↓↓ ВСТАВЬТЕ ЭТОТ БЛОК ЗДЕСЬ ↓↓↓ ###
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Filter dead channels
        run: |
          npm install -g iptv-checker
          iptv-checker -i ru.m3u -o ru_filtered.m3u --timeout 5000
          mv ru_filtered.m3u ru.m3u
      ### ↑↑↑ КОНЕЦ БЛОКА ДЛЯ ВСТАВКИ ↑↑↑ ###
- name: Commit and push changes
  run: |
    git config --global user.name "GitHub Actions"
    git config --global user.email "actions@github.com"
    git add ru.m3u
    git pull --rebase origin main  # Сначала получаем изменения
    git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')"
    git push origin main
    
